export const ALL_BENEFITS = [
  "Acesso à todas as palestras na plenária principal (1 dia)",
  "Lugar reservado mais próximo do palco",
  "Credenciamento antecipado",
  "Kit VIP boas-vindas",
  "Garçom",
  "Open bar (água, refrigerante e energético)",
  "Assentos especiais (sofás/poltronas)",
  "Sala VIP descanso Privilege",
  "Credenciamento VIP (exclusivo)",
  "Credenciamento exclusivo",
  "Sala ambiente reservada",
  "Mesa no mezanino com 4 lugares",
  "4 acessos à todas as palestras na plenária principal (1 dia)",
];

export const TICKETS = [
  {
    title: "A FORJA",
    benefits: ["Acesso à todas as palestras na plenária principal (1 dia)"],
    price: "169,90",
    perMounth: "17,57",
    times: 12,
    color: "orange",
  },
  {
    title: "GOLD",
    benefits: [
      "Acesso à todas as palestras na plenária principal (1 dia)",
      "Lugar reservado mais próximo do palco",
    ],
    price: "289,90",
    perMounth: "29,98",
    times: 12,
    color: "gold",
  },
  {
    title: "VIP",
    benefits: [
      "Acesso à todas as palestras na plenária principal (1 dia)",
      "Lugar reservado mais próximo do palco",
      "Credenciamento antecipado",
      "Kit VIP boas-vindas",
    ],
    price: "429,90",
    perMounth: "42,40",
    times: 12,
    color: "pink",
  },
  {
    title: "PRIVILEGE",
    benefits: [
      "Acesso à todas as palestras na plenária principal (1 dia)",
      "Lugar reservado mais próximo do palco",
      "Assentos especiais (sofás/poltronas)",
      "Credenciamento antecipado",
      "Kit VIP boas-vindas",
      "Garçom",
      "Sala VIP descanso Privilege",
      "Credenciamento VIP (exclusivo)",
      "Open bar (água, refrigerante e energético)",
    ],
    price: "998,99",
    perMounth: "103,32",
    times: 12,
    color: "black",
  },
  {
    title: "TOP FRONT",
    benefits: [
      "4 acessos à todas as palestras na plenária principal (1 dia)",
      "Mesa no mezanino com 4 lugares",
      "Credenciamento antecipado",
      "Kit VIP boas-vindas",
      "Garçom",
      "Credenciamento exclusivo",
      "Open bar (água, refrigerante e energético)",
      "Sala ambiente reservada",
    ],
    price: "2.299,90",
    perMounth: "237,86",
    times: 12,
    color: "black",
  },
  // {
  //   title: "MOVIMENTO Z",
  //   benefits: [
  //     "Acesso à todas as palestras na plenária principal (1 dia)",
  //     "Lugar reservado mais próximo do palco",
  //     "Assentos especiais (sofás/poltronas)",
  //     "Credenciamento antecipado",
  //     "Kit VIP boas-vindas",
  //     "Garçom",
  //     "Sala VIP descanso Privilege",
  //     "Credenciamento VIP (exclusivo)",
  //     "Open bar (água, refrigerante e energético)",
  //   ],
  //   price: "1.199,00",
  //   perMounth: "1.199",
  //   times: 12,
  //   color: "blue",
  // },
];
